steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/gourmet-support-base', '.']
    dir: 'support-base'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/gourmet-support-base']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'gourmet-support-base'
      - '--image'
      - 'gcr.io/$PROJECT_ID/gourmet-support-base'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--port'
      - '8080'
      - '--timeout'
      - '3600'
      - '--session-affinity'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'GEMINI_API_KEY=${_GEMINI_API_KEY},GOOGLE_PLACES_API_KEY=${_GOOGLE_PLACES_API_KEY}'

substitutions:
  _GEMINI_API_KEY: ''
  _GOOGLE_PLACES_API_KEY: ''
